<div class="tabbable"> <!-- Only required for left/right tabs -->
	<ul class="nav nav-tabs">
		<li class="active">
			<a href="#tabResourceGroupsContent" id="tabResourceGroups" data-toggle="tab">Ressursigrupid</a>
		</li>
		<li>
			<a href="#tabRolesContent" id="tabRoles" data-toggle="tab">Kasutajarollid</a>
		</li>
		<li>
			<a href="#tabResourcesContent" id="tabResources" data-toggle="tab">Ressursid</a>
		</li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane active" id="tabResourceGroupsContent">
			<h4>Ressursigrupid
				<a href="<?php echo $this->url('development/query', array(
					'controller' => 'roleGroups',
					'action' => 'add-resource-group',
				)); ?>" class="pull-right fancyboxLink btn btn-mini btn-info "><i class="icon-user icon-plus icon-white"></i> Lisa ressursigrupp</a>
			</h4>
			<?php if (count($this->resourceGroups) > 0): ?>
				<table class="table">
					<tr>
						<th>Identifikaator</th>
						<th>Ressursid</th>
					</tr>
					<?php foreach ($this->resourceGroups as $resourceGroup): /* @var $resourceGroup \BitWebAcl\Entity\BW\ResourceGroup */ ?>
						<tr>
							<td><?php echo $resourceGroup->getIdentificator(); ?></td>
							<td>
								<?php foreach ($resourceGroup->getResources() as $resource): /* @var $resource \BitWebAcl\Entity\BW\Resource */ ?>
									<div>
										<span><?php echo $resource->getController(); ?>::<?php echo $resource->getAction(); ?></span>
										<span>
											<a href="<?php echo $this->url('development/query', array(
												'controller' => 'roleGroups',
												'action' => 'remove-resource-from-group',
												'resourceGroup' => $resourceGroup->getIdentificator(),
												'resource' => $resource->getIdentificator(),
											)); ?>" class="fancyboxLink btn btn-mini btn-danger">
											<i class="icon-remove icon-white"></i></a>
										</span>	
									</div>
								<?php endforeach; ?>
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php else: ?>
				<p class="text-muted">Ressursigrupid puuduvad</p>
			<?php endif; ?>
		</div>
	
		<div class="tab-pane" id="tabRolesContent">
			<h4>Kasutajarollid
				<a href="<?php echo $this->url('development/query', array(
					'controller' => 'roleGroups',
					'action' => 'add-role',
				)); ?>" class="pull-right fancyboxLink btn btn-mini btn-info "><i class="icon-user icon-plus icon-white"></i> Lisa kasutajaroll</a>
			</h4>
			<?php if (count($this->roles) > 0): ?>
				<table class="table">
					<tr>
						<th>Identifikaator</th>
						<th>Seotud ressursigrupid</th>
					</tr>
					<?php foreach ($this->roles as $role): /* @var $role \BitWebAcl\Entity\BW\Role */ ?>
						<tr>
							<td><?php echo $role->getIdentificator(); ?></td>
							<td>
								<?php foreach ($role->getResourceGroups() as $resourceGroup): ?>
									<div><?php echo $resourceGroup->getIdentificator(); ?></div>
								<?php endforeach; ?>
								<a href="<?php echo $this->url('development/query', array(
									'controller' => 'roleGroups',
									'action' => 'add-resource-group-to-role',
									'role' => $role->getIdentificator(),
								)); ?>" class="pull-right fancyboxLink btn btn-mini btn-info "><i class="icon-user icon-plus icon-white"></i> Lisa / Muuda</a>
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php else: ?>
				<p class="text-muted">Kasutajarollid puuduvad</p>
			<?php endif; ?>
		</div>
		
		<div class="tab-pane" id="tabResourcesContent">
			<h4>Ressursid
				<span class="btn-toolbar pull-right">
					<?php if (count($this->resources) > 0): ?>
						<a href="javascript:;" onclick="addResourcesToGroup()"  class="btn btn-mini btn-info "><i class="icon-user icon-plus icon-white"></i> Lisa gruppi</a>
					<?php endif; ?>
					<a href="<?php echo $this->url('development/query', array(
						'controller' => 'roleGroups',
						'action' => 'update-resources',
					)); ?>" class="btn btn-mini btn-info "><i class="icon-user icon-repeat icon-white"></i> Genereeri / uuenda</a>
				</span>
			</h4>
			<?php if (count($this->resources) > 0): ?>
				<form action="<?php echo $this->url('development/query', array(
						'controller' => 'roleGroups',
						'action' => 'add-resources-to-group'	
					)); ?>" id="resourcesForm" method="post">
					<table class="table">
						<thead>
							<tr>
								<th>Controller</th>
								<th>Action</th>
								<th>Vali</th>
								<th>Tegevus</th>
							</tr>
						</thead>
						<tbody>
							<?php $previousAlias = null; ?>
							<?php foreach ($this->resources as $resource): /* @var $resource \BitWebAcl\Entity\BW\Resource */ ?>
								<tr>
									<td class="<?php if ($resource->getAlias() == $previousAlias): ?>muted<?php endif; ?>">
										<div><?php echo $resource->getController(); ?></div>
										<div><?php echo $resource->getAlias(); ?></div>	
									</td>
									<td><?php echo $resource->getAction(); ?></td>
									<td>
										<input type="checkbox" name="resources[<?php echo $resource->getIdentificator(); ?>]">					
									</td>
									<td>
										<a href="<?php echo $this->url('development/query', array (
											'controller' => 'role-group',
											'action' => 'remove-resource',
											'resource' => $resource->getIdentificator(),
										));?>" class="fancyboxLink btn btn-mini btn-danger">
											<i class="icon-remove icon-white"></i>
										</a>
									</td>
								</tr>
								<?php $previousAlias = $resource->getAlias(); ?>
							<?php endforeach; ?>
						</tbody>
					</table>
				</form>
				<script type="text/javascript">
					function addResourcesToGroup() {
						document.getElementById('resourcesForm').submit();
					}
				</script>
			<?php else: ?>
				<p class="text-muted">Ressursid puuduvad</p>
			<?php endif; ?>
		</div>
	</div>
</div>

<script type="text/javascript">
	var hash = window.location.hash;
	if (hash != null) {
		$(hash).tab('show');
	}
</script>