<script type="text/javascript">

var EntityGeneratorManager = {
	allChecked: false,
	checkAllEntities: function() {
		if (EntityGeneratorManager.allChecked) {
			$('.entityCheckbox').removeAttr('checked');
			$('#checkAllButton').val('Kõik!');
			EntityGeneratorManager.allChecked = false;
		} else {
			$('.entityCheckbox').attr('checked', 'checked');
			$('#checkAllButton').val('Mitte ükski!');
			EntityGeneratorManager.allChecked = true;
		}
	}		
}


</script>
<h1>Entity generaator</h1>
<form action="<?php echo $this->url('development', array('controller'=>'entity', 'action'=>'generate-entities')); ?>" method="post">
	<table class="table">
		<tr>
			<th colspan="2">Seaded</th>
		</tr>
		<tr>
			<td>Vanemklass:</td>
			<td>
				<select name="parentClassName">
					<option value="">-Puudub-</option>
					<option value="AbstractEntity" selected="selected">\BitWebExtension\Entity\AbstractEntity</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>Mooduli nimi:</td>
			<td>
				<input class="input-block-level" type="text" name="moduleName" value="Application">
			</td>
		</tr>
	</table>
	<table class="table table-striped">
		<tr>
			<td colspan="3" style="text-align:right;">
				<input class="btn btn-primary" type="submit" value="Genereeri klassid">
			</td>
		</tr>
		<tr>
			<th>Nimi</th>
			<th>Kas olemas</th>
			<th>
				<div style="width:100px;text-align:right;">
					<input class="btn btn-info" type="button" onclick="EntityGeneratorManager.checkAllEntities()" id="checkAllButton" value="Kõik!">
				</div>
			</th>
		</tr>
		<?php foreach($this->classNames as $className): ?>
			<?php $filePath = $className['path']. '/' . $className['namespace'] . '/' . $className['entityName'] . '.php'; ?>
			<tr>
				<td>
					<u><?php echo $className['className']; ?></u>
					<?php if ($className['entityName'] != $className['className']): ?>
						<?php echo '<u>' . $className['className'] . '</u><br> <small>' . $className['entityName'] . '</small>'; ?>
					<?php endif; ?> 
				</td>
				<td><?php echo ((file_exists($filePath))?$filePath:' - '); ?></td>
				<td style="text-align:center;">
					<input type="checkbox" class="entityCheckbox" name="classNames[]" value="<?php echo $className['className']; ?>">
				</td>
			</tr>
		<?php endforeach; ?>
		<tr>
			<td colspan="3" style="text-align:right;">
				<input class="btn btn-primary" type="submit" value="Genereeri klassid">
			</td>
		</tr>
	</table>
</form>

