<?php use Development\Service\RoleService; ?>
<?php $roles = $this->roles; ?>
<h1>Rollihaldus</h1>
<?php if (!$this->isRoleMappingDefined): ?>
	<p class="text-error">Defineerimata on konfiguratioonis acl->roleMapping. Genereeritav konfiguratsioon ei asenda klassikonstante!</p>
<?php endif; ?>
<?php switch ($this->usedAclConfiguration): 
	case RoleService::ACL_TYPE_PROJECT: ?>
	<p class="muted">Kuva on genereeritud projekti ACL konfiguratsiooni põhjal<p>
	<?php break;
	case RoleService::ACL_TYPE_NONE: ?>
	<p class="text-warning">Projekti ACL konfiguratsiooni ei leitud.<p>
	<?php break; 
	case RoleService::ACL_TYPE_GENERATED?>
	<p class="text-warning">Kuva on genereeritud genereerimisel oleva ACL konfiguratsiooni põhjal, mida projektis veel pruugi olla.<p>
	<?php break; ?>
<?php endswitch; ?>
<table class="table">
	<thead>
		<?php echo $this->partial('development/role/index/header-row'); ?>
	</thead>
	<tbody>
		<?php foreach ($this->controllersData as $key => $controllerData): ?>
			<?php if ($key !== 0 && !($key % 5)): ?>
				<?php echo $this->partial('development/role/index/header-row'); ?>
			<?php endif; ?>
			<?php if (count((array)$controllerData['actions']) > 0): ?>
				<?php foreach ((array)$controllerData['actions'] as $key => $action): ?>	
					<tr id="<?php echo stripslashes($controllerData['controller']['class']); ?>">
						<?php if ($key == 0): ?>
							<td rowspan="<?php echo count($controllerData['actions']) + 1; ?>">
								<strong class="text-info"><?php echo $controllerData['controller']['class']; ?></strong>
							</td>	
						<?php endif; ?>
						<td>
							
							<?php if ($action !== 'all'): ?>
								<span><?php echo $action; ?></span>
								<a href="<?php echo $this->url('development/query', array(
									'controller' => 'role',
									'action' => 'remove-action',
									'moduleName' => $controllerData['controller']['module'],	
									'controllerResourceName' => $controllerData['controller']['resourceName'],
									'controllerClass' => $controllerData['controller']['class'],
									'actionName' => $action,
								));?>" class="fancyboxLink btn btn-mini btn-danger">
									<i class="icon-remove icon-white"></i>
								</a>
							<?php else: ?>
								<strong><?php echo $action; ?></strong>
							<?php endif; ?>	
						</td>
						<td style="text-align:right;">
							<ul class="unstyled" style="text-align:right;">
								<?php foreach ((array)$controllerData['controller']['actions']['allowed'][$action] as $roles): ?>
									<li>
										<div>
											<ul class="unstyled">
												<?php foreach ((array)$roles as $role): ?>
													<li>
														<?php echo $role; ?>
														<a href="<?php echo $this->url('development/query', array (
															'controller' => 'role',
															'action' => 'remove-role',
															'moduleName' => $controllerData['controller']['module'],
															'controllerResourceName' => $controllerData['controller']['resourceName'],
															'controllerClass' => $controllerData['controller']['class'],
															'list' => 'allow',
															'actionName' => $action,
															'role' => $role
														));?>" class="fancyboxLink btn btn-mini btn-danger">
															<i class="icon-remove icon-white"></i>
														</a>
													</li>
												<?php endforeach; ?>
											</ul>
										</div>
									</li>
								<?php endforeach; ?>
							</ul>
							<div>
								<a href="<?php echo $this->url('development/query', array (
									'controller' => 'role',
									'action' => 'add-role',	
									'moduleName' => $controllerData['controller']['module'],
									'controllerResourceName' => $controllerData['controller']['resourceName'],
									'controllerClass' => $controllerData['controller']['class'],
									'list' => 'allow',
									'actionName' => $action,
								));?>" class="fancyboxLink btn btn-mini btn-info">
									<i class="icon-user icon-plus icon-white"></i><i class="icon-user icon-white"></i>
								</a>
							</div>
						</td>
						<td style="text-align:right;">
							<ul class="unstyled">
								<?php foreach ((array)$controllerData['controller']['actions']['denyed'][$action] as $roles): ?>
									<li>
										<div>
											<ul class="unstyled">
												<?php foreach ((array)$roles as $role): ?>
													<li>
														<?php echo $role; ?>
														<a href="<?php echo $this->url('development/query', array (
															'controller' => 'role',
															'action' => 'remove-role',
															'moduleName' => $controllerData['controller']['module'],
															'controllerResourceName' => $controllerData['controller']['resourceName'],
															'controllerClass' => $controllerData['controller']['class'],
															'list' => 'deny',
															'actionName' => $action,
															'role' => $role
														));?>" class="fancyboxLink btn btn-mini btn-danger">
															<i class="icon-remove icon-white"></i>
														</a>
													</li>
												<?php endforeach; ?>
											</ul>
										</div>
									</li>
								<?php endforeach; ?>
							</ul>
							<div>
								<a href="<?php echo $this->url('development/query', array (
										'controller' => 'role',
										'action' => 'add-role',
										'moduleName' => $controllerData['controller']['module'],
										'controllerResourceName' => $controllerData['controller']['resourceName'],
										'controllerClass' => $controllerData['controller']['class'],
										'list' => 'deny',
										'actionName' => $action,
									));?>" class="fancyboxLink btn btn-mini btn-info">
									<i class="icon-user icon-plus icon-white"></i><i class="icon-user icon-white"></i>
								</a>
							</div>
						</td>
					</tr>
				<?php endforeach; ?>
				<tr>
					<td colspan="3">
						<a href="<?php echo $this->url('development/query', array (
							'controller' => 'role',
							'action' => 'add-action',
							'moduleName' => $controllerData['controller']['module'],	
							'controllerResourceName' => $controllerData['controller']['resourceName'],
							'controllerClass' => $controllerData['controller']['class'],
						));?>" class="fancyboxLink btn btn-mini btn-info"><i class="icon-user icon-plus icon-white"></i> Lisa action</a>
					</td>
				</tr>
			<?php else: ?>
				<tr>
					<td>
						<strong><?php echo $controllerData['controller']['class']; ?></strong>
					</td>
					<td colspan="3">
						<p class="text-error">Ühtegi actionit või controllerit ennast ei ole ACL-is defineeritud.
							<a href="<?php echo $this->url('development/query', array (
								'controller' => 'role',
								'action' => 'add-controller',
								'moduleName' => $controllerData['controller']['module'],	
								'controllerClass' => $controllerData['controller']['class'],
							));?>" class="fancyboxLink btn btn-mini btn-warning"><i class="icon-user icon-plus icon-white"></i> Lisa controller</a>
						</p>
					</td>
				</tr>	
			<?php endif; ?>
		<?php endforeach; ?>
	</tbody>
</table>