<h4>Lisa ressursid gruppi</h4>
<form action="" method="post">
	<?php if (count($this->groups) > 0): ?>
		<label>Vali olemasolev grupp:
			<select name="grupid" id="groupIdentificatorSelect" onchange="groupIdentificatorChanged()" onclick="groupIdentificatorChanged()">
				<?php foreach ($this->groups as $group): /* @var $group \BitWebAcl\Entity\BW\ResourceGroup */ ?>
					<option value="<?php echo $group->getIdentificator(); ?>"><?php echo $group->getIdentificator(); ?></option>
				<?php endforeach; ?>
			</select>
		</label>
	<?php endif; ?>
	<label style="width:200px;">Grupi identifikaator: <input class="input-block-level" id="groupIdentificatorInputText" type="text" name="groupIdentificator"></label>
	<h5>Valitud ressursid:</h5>
	<?php foreach ($this->resources as $resource): /* @var $resource \BitWebAcl\Entity\BW\Resource */ ?>
		<label class="checkbox"><input type="checkbox" checked="checked" name="resources[<?php echo $resource->getIdentificator(); ?>]"><?php echo $resource->getController() . ' - ' . $resource->getAction(); ?></label>
	<?php endforeach; ?>
	<input class="btn btn-primary" type="submit" value="Lisa">
	<input class="btn btn-danger" type="button" value="Tagasi" onclick="javascript:back('tabResources');">
</form>
<script type="text/javascript">
	function groupIdentificatorChanged() {
		var select = document.getElementById('groupIdentificatorSelect');
		if (select !== undefined) {
			var value = select.options[select.selectedIndex].value;
			document.getElementById('groupIdentificatorInputText').value = value;
		}
	}
	groupIdentificatorChanged();
</script>