<?php if (count($this->actions) > 0): ?>
	<form action="<?php echo $this->url('development/query', array(), array(), true); ?>" method="post">
		<?php foreach ($this->actions as $action): ?>
			<label><input type="checkbox" name="actionNames[]" value="<?php echo $action; ?>"><?php echo $action?></label> 
		<?php endforeach; ?>
		<!-- label class="control-label">Kirjuta actioni nimi: <input class="input-block-level" type="text" name="actionName"></label -->
		<input class="btn btn-primary" type="submit" value="Lisa">
		<input class="btn btn-danger" type="button" value="Tagasi" onclick="javascript:parent.$.fancybox.close();">
	</form>
<?php else: ?>
	<h4>Ühtegi actionit ei leitud valitud controllerist</h4>
<?php endif; ?>