<?php if (isset($this->display_not_found_reason) && $this->display_not_found_reason): ?>
	<h1>A 404 error occurred</h1>
	<h2><?php echo $this->message ?></h2>
	<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
		<h3>Exception information:</h3>
		<p>
		    <h4>Message:</h4>
		    <pre><?php echo $this->exception->getMessage() ?></pre>
		    <h4>Stack trace:</h4>
		    <pre><?php echo $this->exception->getTraceAsString() ?></pre>
		</p>
	<?php else: ?>
		<h3>No Exception available</h3>
	<?php endif ?>
<?php else: ?>
	<h1>404</h1>
<?php endif ?>